/**
 * Dumps the development laureate-attributed challenge solutions to a committed
 * JSON snapshot that the API server seeds into an empty database on boot.
 *
 * Replit's publish flow syncs the database SCHEMA from dev to prod but never
 * copies data. The Nobel-laureate solutions generated by `seed-nobel-solutions`
 * live only in the dev DB, so this snapshot is the bridge: re-run it whenever
 * the dev data changes, commit the result, and the server's boot-time seeder
 * (`seedNobelSolutions`) will populate any empty production database from it.
 *
 * Only system-authored rows (userId IS NULL) whose authorSlug maps to a
 * featured profile with a non-empty `nobelPrizes` array are captured — user
 * submissions and non-laureate contributors are left out.
 *
 * Usage:
 *   pnpm --filter @workspace/scripts run dump-nobel-solutions
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { sql, asc, eq, isNull, and } from "drizzle-orm";
import {
  db,
  pool,
  challengeSolutionsTable,
  featuredProfilesTable,
} from "@workspace/db";

const OUT_PATH = resolve(
  import.meta.dirname,
  "../../artifacts/api-server/src/data/nobel-solutions.json",
);

async function main(): Promise<void> {
  const rows = await db
    .select({
      challengeSlug: challengeSolutionsTable.challengeSlug,
      authorName: challengeSolutionsTable.authorName,
      authorSlug: challengeSolutionsTable.authorSlug,
      title: challengeSolutionsTable.title,
      description: challengeSolutionsTable.description,
      approach: challengeSolutionsTable.approach,
      link: challengeSolutionsTable.link,
    })
    .from(challengeSolutionsTable)
    .innerJoin(
      featuredProfilesTable,
      eq(challengeSolutionsTable.authorSlug, featuredProfilesTable.slug),
    )
    .where(
      and(
        isNull(challengeSolutionsTable.userId),
        sql`jsonb_array_length(${featuredProfilesTable.nobelPrizes}) > 0`,
      ),
    )
    .orderBy(asc(challengeSolutionsTable.authorSlug), asc(challengeSolutionsTable.challengeSlug));

  writeFileSync(OUT_PATH, JSON.stringify(rows, null, 2) + "\n", "utf8");
  console.log(`Wrote ${rows.length} laureate solutions to ${OUT_PATH}`);
  await pool.end();
}

main().catch(async (err) => {
  console.error(err);
  await pool.end();
  process.exit(1);
});
