import type { InsertChallenge } from "@workspace/db";

export interface ChallengeTeam {
  name: string;
  description: string;
  url: string;
}

export interface ChallengeWithTeams extends InsertChallenge {
  teams: ChallengeTeam[];
}

export const CHALLENGES: ChallengeWithTeams[] = [
  {
    slug: "climate-change",
    title: "Halt Catastrophic Climate Change",
    domain: "climate",
    urgency: "critical",
    summary: "Limit global warming to 1.5°C to prevent irreversible damage to ecosystems and human civilization.",
    whyItMatters: "Unchecked climate change threatens to displace billions, collapse food systems, and trigger mass extinctions. Every fraction of a degree matters — the difference between 1.5°C and 2°C represents hundreds of millions of lives and the survival of entire island nations.",
    teamsJson: "[]",
    teams: [
      { name: "IPCC", description: "Intergovernmental Panel on Climate Change — the UN body for climate science assessments.", url: "https://www.ipcc.ch" },
      { name: "Project Drawdown", description: "Mapping and ranking the most substantive solutions to reduce greenhouse gases.", url: "https://drawdown.org" },
      { name: "Climate TRACE", description: "Independent global inventory tracking greenhouse gas emissions in near-real time.", url: "https://climatetrace.org" },
    ],
  },
  {
    slug: "clean-energy-access",
    title: "Universal Access to Clean Energy",
    domain: "energy",
    urgency: "critical",
    summary: "Provide affordable, reliable, and sustainable energy to the 750 million people still without electricity.",
    whyItMatters: "Energy poverty traps communities in cycles of deprivation. Without electricity, hospitals can't refrigerate vaccines, children can't study after dark, and economies can't grow. Clean energy access is the master key to the SDGs.",
    teamsJson: "[]",
    teams: [
      { name: "IRENA", description: "International Renewable Energy Agency — driving the global energy transition.", url: "https://www.irena.org" },
      { name: "Energy for Growth Hub", description: "Research and policy network accelerating modern energy access in developing countries.", url: "https://energyforgrowth.org" },
      { name: "GOGLA", description: "Global off-grid solar market association representing 170+ companies.", url: "https://www.gogla.org" },
    ],
  },
  {
    slug: "pandemic-preparedness",
    title: "Prevent the Next Pandemic",
    domain: "health",
    urgency: "critical",
    summary: "Build global systems to detect, contain, and neutralise novel pathogens before they become pandemics.",
    whyItMatters: "COVID-19 killed millions and cost the global economy over $12 trillion. The next pandemic could be worse. We need a 100-day vaccine platform, real-time pathogen surveillance, and global stockpile treaties before the next threat emerges.",
    teamsJson: "[]",
    teams: [
      { name: "CEPI", description: "Coalition for Epidemic Preparedness Innovations — funding vaccines for future outbreaks.", url: "https://cepi.net" },
      { name: "Global Health Security Agenda", description: "Partnership of 70+ countries building capacity to prevent and detect outbreaks.", url: "https://ghsagenda.org" },
      { name: "Ginkgo Bioworks", description: "Biosecurity division running biosurveillance programs for novel pathogen detection.", url: "https://www.ginkgobioworks.com" },
    ],
  },
  {
    slug: "ocean-health",
    title: "Restore Ocean Health",
    domain: "biodiversity",
    urgency: "high",
    summary: "Reverse ocean acidification, overfishing, and plastic pollution to restore marine ecosystems by 2050.",
    whyItMatters: "Oceans produce half of Earth's oxygen, absorb 25% of CO₂, and feed over 3 billion people. As acidity rises and fish stocks collapse, so does the planet's ability to support life. The ocean is Earth's life-support system.",
    teamsJson: "[]",
    teams: [
      { name: "Ocean Conservancy", description: "Science-based advocacy for protecting the ocean from major threats.", url: "https://oceanconservancy.org" },
      { name: "Pristine Seas (National Geographic)", description: "Exploring and protecting the last wild places in the ocean.", url: "https://www.nationalgeographic.org/projects/pristine-seas" },
      { name: "The Ocean Cleanup", description: "Developing advanced technologies to rid the world's oceans of plastic.", url: "https://theoceancleanup.com" },
    ],
  },
  {
    slug: "food-security",
    title: "End Global Hunger and Food Insecurity",
    domain: "food",
    urgency: "critical",
    summary: "Feed a world of 10 billion people sustainably while halving food waste and ending malnutrition.",
    whyItMatters: "828 million people go to bed hungry every night, while a third of all food produced is wasted. Climate change threatens crop yields just as population peaks. Solving food security means redesigning agriculture, supply chains, and diets simultaneously.",
    teamsJson: "[]",
    teams: [
      { name: "CGIAR", description: "Global partnership researching food security and sustainable agriculture.", url: "https://www.cgiar.org" },
      { name: "World Food Programme", description: "UN agency delivering food assistance and working for zero hunger.", url: "https://www.wfp.org" },
      { name: "Eat Forum", description: "Science-policy-business platform for transforming global food systems.", url: "https://eatforum.org" },
    ],
  },
  {
    slug: "clean-water",
    title: "Safe Water and Sanitation for All",
    domain: "water",
    urgency: "critical",
    summary: "Ensure universal access to safe drinking water and sanitation, and prevent global water scarcity.",
    whyItMatters: "2 billion people lack access to safe drinking water. By 2030, half the world could face water stress. Waterborne disease kills 1.4 million children annually. Water is the thread running through every other crisis — conflict, food, health.",
    teamsJson: "[]",
    teams: [
      { name: "Water.org", description: "Matt Damon & Gary White's NGO providing safe water access via microfinance.", url: "https://water.org" },
      { name: "OECD Water Governance Programme", description: "Cross-government framework for sustainable water policy.", url: "https://www.oecd.org/water" },
      { name: "Xylem Inc.", description: "Water technology company developing smart infrastructure for water management.", url: "https://www.xylem.com" },
    ],
  },
  {
    slug: "ai-safety",
    title: "Align Artificial Intelligence with Human Values",
    domain: "AI safety",
    urgency: "critical",
    summary: "Ensure advanced AI systems remain safe, interpretable, and aligned with human values as they surpass human capabilities.",
    whyItMatters: "AI is advancing faster than our ability to understand or control it. Misaligned superintelligent systems could pose existential risks. Solving alignment before transformative AI arrives may be the most important problem humanity has ever faced.",
    teamsJson: "[]",
    teams: [
      { name: "Anthropic", description: "AI safety company researching interpretability and constitutional AI.", url: "https://www.anthropic.com" },
      { name: "Center for Human-Compatible AI (CHAI)", description: "UC Berkeley lab developing AI that is provably beneficial to humans.", url: "https://humancompatible.ai" },
      { name: "Machine Intelligence Research Institute", description: "Research nonprofit focused on existential risk from misaligned AI.", url: "https://intelligence.org" },
    ],
  },
  {
    slug: "antibiotic-resistance",
    title: "Stop the Antibiotic Resistance Crisis",
    domain: "health",
    urgency: "critical",
    summary: "Develop new antimicrobials and stewardship frameworks before drug-resistant infections become untreatable.",
    whyItMatters: "Antimicrobial resistance already kills 1.3 million people a year and is on track to kill 10 million annually by 2050 — more than cancer. Routine surgeries could once again become fatal without effective antibiotics.",
    teamsJson: "[]",
    teams: [
      { name: "CARB-X", description: "Public-private partnership accelerating antibacterial research globally.", url: "https://carb-x.org" },
      { name: "AMR Action Fund", description: "$1B fund bridging the antibiotic development gap.", url: "https://amractionfund.com" },
      { name: "WHO AMR Division", description: "UN-led global action plan on antimicrobial resistance.", url: "https://www.who.int/antimicrobial-resistance" },
    ],
  },
  {
    slug: "biodiversity-loss",
    title: "Halt the Sixth Mass Extinction",
    domain: "biodiversity",
    urgency: "critical",
    summary: "Protect and restore biodiversity to stop the collapse of ecosystems that all life — including humanity — depends on.",
    whyItMatters: "We are losing species 1,000× faster than natural background rates. The collapse of pollinators, soil organisms, and keystone predators unravels the food webs that sustain agriculture and wild ecosystems. Biodiversity loss is an existential threat hiding in plain sight.",
    teamsJson: "[]",
    teams: [
      { name: "IUCN", description: "International Union for Conservation of Nature — the global authority on species status.", url: "https://www.iucn.org" },
      { name: "Rewilding Europe", description: "Restoring wildlife and wild lands across Europe at landscape scale.", url: "https://rewildingeurope.com" },
      { name: "Revive & Restore", description: "Genetic rescue of endangered and extinct species using biotechnology.", url: "https://reviverestore.org" },
    ],
  },
  {
    slug: "mental-health-crisis",
    title: "Solve the Global Mental Health Crisis",
    domain: "mental health",
    urgency: "high",
    summary: "Make evidence-based mental health care accessible to the 1 billion people worldwide who suffer from mental health disorders.",
    whyItMatters: "Depression and anxiety cost the global economy $1 trillion per year in lost productivity. Suicide kills more people than war and homicide combined. Yet 75% of those with mental illness receive no treatment at all. The treatment gap is one of the great injustices of modern medicine.",
    teamsJson: "[]",
    teams: [
      { name: "Wellcome Trust Mental Health", description: "Major funder of research into depression, anxiety and psychosis.", url: "https://wellcome.org/what-we-do/mental-health" },
      { name: "One Mind", description: "Alliance accelerating brain health research and global advocacy.", url: "https://onemind.org" },
      { name: "Strong Minds", description: "Scaling group therapy for depression in sub-Saharan Africa.", url: "https://strongminds.org" },
    ],
  },
  {
    slug: "global-inequality",
    title: "Reduce Extreme Global Inequality",
    domain: "inequality",
    urgency: "high",
    summary: "Narrow the gap between the world's richest and poorest people through systemic economic and policy reform.",
    whyItMatters: "The richest 1% own more wealth than the bottom 50% combined. Extreme inequality undermines democracy, fuels conflict, and means billions live without opportunities they deserve. No civilization can call itself advanced while billions are left behind.",
    teamsJson: "[]",
    teams: [
      { name: "Oxfam International", description: "Global movement working to end the injustice of poverty.", url: "https://www.oxfam.org" },
      { name: "GiveDirectly", description: "Sending cash directly to people living in extreme poverty.", url: "https://www.givedirectly.org" },
      { name: "World Inequality Lab", description: "Research program tracking inequality and its drivers worldwide.", url: "https://wid.world" },
    ],
  },
  {
    slug: "education-access",
    title: "Quality Education for Every Child",
    domain: "education",
    urgency: "high",
    summary: "Close the global learning gap so every child can access high-quality education regardless of geography or income.",
    whyItMatters: "300 million children are out of school or learning so little that school barely helps them. Education is the most powerful lever for human development — it reduces poverty, improves health, and enables innovation. The learning crisis is the injustice that perpetuates all others.",
    teamsJson: "[]",
    teams: [
      { name: "Khan Academy", description: "Free, world-class education for anyone, anywhere.", url: "https://www.khanacademy.org" },
      { name: "Pratham", description: "India's largest education NGO pioneering the Teaching at the Right Level approach.", url: "https://www.pratham.org" },
      { name: "Education Cannot Wait", description: "UN fund for education in emergencies and protracted crises.", url: "https://www.educationcannotwait.org" },
    ],
  },
  {
    slug: "nuclear-disarmament",
    title: "Eliminate Nuclear Weapons",
    domain: "peace",
    urgency: "critical",
    summary: "Achieve a world free of nuclear weapons before miscalculation or terrorism triggers a catastrophic exchange.",
    whyItMatters: "9 nations hold 12,500 nuclear warheads capable of ending civilization. Near-misses in 1983 and 1995 show how close we came to accidental nuclear war. A single nuclear exchange between regional powers would trigger a nuclear winter killing billions indirectly.",
    teamsJson: "[]",
    teams: [
      { name: "ICAN", description: "Nobel Peace Prize–winning campaign for the Treaty on the Prohibition of Nuclear Weapons.", url: "https://www.icanw.org" },
      { name: "Ploughshares Fund", description: "Philanthropic foundation funding nuclear security and disarmament.", url: "https://www.ploughshares.org" },
      { name: "Bulletin of the Atomic Scientists", description: "Expert analysis on nuclear risk, including the Doomsday Clock.", url: "https://thebulletin.org" },
    ],
  },
  {
    slug: "alzheimers-dementia",
    title: "Cure Alzheimer's and Dementia",
    domain: "health",
    urgency: "high",
    summary: "Understand and defeat the neurodegenerative diseases that rob millions of their minds and burden families worldwide.",
    whyItMatters: "55 million people live with dementia today — a number set to triple by 2050 as populations age. The disease costs $1.3 trillion annually and is utterly devastating for patients and caregivers. We still have no disease-modifying treatment for Alzheimer's.",
    teamsJson: "[]",
    teams: [
      { name: "Alzheimer's Association", description: "Largest non-profit funder of Alzheimer's research in the US.", url: "https://www.alz.org" },
      { name: "Dementia Research Institute (UK DRI)", description: "UK's biggest dementia research initiative across six university hubs.", url: "https://ukdri.ac.uk" },
      { name: "Alector", description: "Biotech pioneering neuroinflammation-focused approaches to dementia.", url: "https://www.alector.com" },
    ],
  },
  {
    slug: "plastic-pollution",
    title: "End Plastic Pollution",
    domain: "climate",
    urgency: "high",
    summary: "Stop the flow of plastic waste into nature and redesign the global plastics economy toward circularity.",
    whyItMatters: "8 million tonnes of plastic enter the oceans every year. Microplastics are now found in human blood, breast milk, and Antarctic ice cores. Plastic production is set to triple by 2060 without intervention, poisoning ecosystems and food chains irreversibly.",
    teamsJson: "[]",
    teams: [
      { name: "Break Free from Plastic", description: "Global movement working toward a world free of plastic pollution.", url: "https://www.breakfreefromplastic.org" },
      { name: "Plastic Bank", description: "Stopping ocean plastic while improving lives of collectors in developing nations.", url: "https://plasticbank.com" },
      { name: "Ellen MacArthur Foundation", description: "Accelerating the transition to a circular economy for plastics.", url: "https://www.ellenmacarthurfoundation.org" },
    ],
  },
  {
    slug: "cancer-moonshot",
    title: "Cure Cancer",
    domain: "health",
    urgency: "high",
    summary: "Develop universal cancer detection and treatments so that a cancer diagnosis is no longer a death sentence.",
    whyItMatters: "Cancer kills 10 million people a year — one in six deaths globally. Many cancers caught early are curable, yet early detection remains out of reach for billions. New immunotherapy and cell-therapy breakthroughs hint at a world where most cancers are treatable.",
    teamsJson: "[]",
    teams: [
      { name: "Cancer Research UK", description: "Europe's largest cancer research charity funding 4,000+ scientists.", url: "https://www.cancerresearchuk.org" },
      { name: "Parker Institute for Cancer Immunotherapy", description: "Accelerating the development of breakthrough immune therapies.", url: "https://www.parkerici.org" },
      { name: "GRAIL", description: "Early cancer detection using multi-cancer early detection blood tests.", url: "https://grail.com" },
    ],
  },
  {
    slug: "freshwater-scarcity",
    title: "Prevent Global Freshwater Collapse",
    domain: "water",
    urgency: "high",
    summary: "Protect freshwater aquifers, rivers, and wetlands from over-extraction and pollution to avert civilizational water crisis.",
    whyItMatters: "70% of freshwater goes to agriculture, yet half is wasted through inefficient irrigation. Major aquifers are being drawn down faster than they refill. The Aral Sea, once the world's fourth-largest lake, no longer exists. Water wars may define the 21st century.",
    teamsJson: "[]",
    teams: [
      { name: "World Resources Institute — Water", description: "Aqueduct tool and policy research on global freshwater risk.", url: "https://www.wri.org/water" },
      { name: "International Water Management Institute", description: "Research on sustainable use of water and land resources.", url: "https://www.iwmi.cgiar.org" },
      { name: "The Nature Conservancy — Water", description: "Market-based approaches to freshwater conservation.", url: "https://www.nature.org/en-us/what-we-do/our-priorities/provide-food-and-water-sustainably" },
    ],
  },
  {
    slug: "refugee-displacement",
    title: "Protect and Integrate 100 Million Displaced People",
    domain: "inequality",
    urgency: "high",
    summary: "Develop humane, durable solutions for the 100+ million forcibly displaced people worldwide.",
    whyItMatters: "Forced displacement has hit record highs every year for a decade. Refugees and internally displaced people are among the world's most vulnerable, yet receive inadequate legal protection and economic integration. Climate change will displace hundreds of millions more.",
    teamsJson: "[]",
    teams: [
      { name: "UNHCR", description: "UN Refugee Agency protecting and supporting the world's displaced people.", url: "https://www.unhcr.org" },
      { name: "International Rescue Committee", description: "Responding to humanitarian crises and helping rebuild shattered lives.", url: "https://www.rescue.org" },
      { name: "Tent Partnership for Refugees", description: "Mobilising the private sector to include refugees in the economy.", url: "https://www.tent.org" },
    ],
  },
  {
    slug: "deforestation",
    title: "End Deforestation and Restore Forests",
    domain: "biodiversity",
    urgency: "critical",
    summary: "Halt all deforestation and restore 350 million hectares of degraded forest to absorb carbon and protect biodiversity.",
    whyItMatters: "Forests are the lungs of the Earth — absorbing carbon, cycling water, and sheltering 80% of terrestrial species. We lose a football field of forest every second. The Amazon is approaching a tipping point where it transitions from carbon sink to carbon source.",
    teamsJson: "[]",
    teams: [
      { name: "Rainforest Alliance", description: "Protecting forests and the people who depend on them.", url: "https://www.rainforest-alliance.org" },
      { name: "Trillion Trees", description: "Partnership of WWF, BirdLife, and WCS to protect and restore a trillion trees.", url: "https://www.trilliontrees.org" },
      { name: "One Tree Planted", description: "Non-profit planting trees globally with corporate and individual partners.", url: "https://onetreeplanted.org" },
    ],
  },
  {
    slug: "longevity",
    title: "Defeat Aging and Age-Related Disease",
    domain: "health",
    urgency: "medium",
    summary: "Understand the biology of aging well enough to extend healthy human lifespan by decades.",
    whyItMatters: "Aging is the root cause of most chronic disease. Cardiovascular disease, cancer, diabetes, and neurodegeneration all accelerate with age. Adding even 5–10 healthy years to the average lifespan would reduce suffering more than curing any single disease.",
    teamsJson: "[]",
    teams: [
      { name: "Calico (Alphabet)", description: "Research lab investigating the biology that controls human lifespan.", url: "https://www.calicolabs.com" },
      { name: "SENS Research Foundation", description: "Developing rejuvenation biotechnologies to repair cellular damage.", url: "https://www.sens.org" },
      { name: "Buck Institute for Research on Aging", description: "World's first independent research institute dedicated to aging.", url: "https://www.buckinstitute.org" },
    ],
  },
  {
    slug: "digital-divide",
    title: "Close the Global Digital Divide",
    domain: "education",
    urgency: "high",
    summary: "Connect the 2.7 billion people who remain offline and ensure the internet is a tool for empowerment, not exclusion.",
    whyItMatters: "Digital exclusion is the 21st century's greatest inequality amplifier. The offline half of humanity is locked out of jobs, healthcare, education, and financial services. AI will widen this divide catastrophically if we don't act now.",
    teamsJson: "[]",
    teams: [
      { name: "Alliance for Affordable Internet (A4AI)", description: "Coalition reducing barriers to affordable internet access globally.", url: "https://a4ai.org" },
      { name: "Internet Society", description: "Non-profit promoting the open development and use of the internet.", url: "https://www.internetsociety.org" },
      { name: "Meta Connectivity", description: "Connecting billions through open-source tools, satellites, and community networks.", url: "https://connectivity.fb.com" },
    ],
  },
  {
    slug: "soil-degradation",
    title: "Reverse Soil Degradation and Desertification",
    domain: "food",
    urgency: "high",
    summary: "Restore the world's depleted and eroded soils before we lose the productive capacity to feed humanity.",
    whyItMatters: "Topsoil is being lost 10–100× faster than it forms. 40% of agricultural land is already degraded. Without soil, there is no agriculture, no food security, and no terrestrial biodiversity. We could run out of fertile topsoil within 60 harvests.",
    teamsJson: "[]",
    teams: [
      { name: "4 per 1000 Initiative", description: "Global program to increase carbon stocks in agricultural soils.", url: "https://www.4p1000.org" },
      { name: "Soil Association", description: "UK charity championing organic farming and healthy soils.", url: "https://www.soilassociation.org" },
      { name: "Commonland", description: "Landscape restoration projects combating land degradation at scale.", url: "https://www.commonland.com" },
    ],
  },
  {
    slug: "clean-air",
    title: "End Air Pollution",
    domain: "health",
    urgency: "high",
    summary: "Eliminate the air pollution that kills 7 million people every year and stunts the development of billions more.",
    whyItMatters: "Air pollution is the world's largest environmental health risk. 99% of people breathe air that exceeds WHO safe limits. Particulate matter causes heart disease, stroke, lung cancer, and cognitive decline. In South Asia and Africa, it robs children of IQ points before they reach school.",
    teamsJson: "[]",
    teams: [
      { name: "Clean Air Fund", description: "Philanthropic initiative tackling air pollution across the world.", url: "https://www.cleanairfund.org" },
      { name: "Health Effects Institute", description: "Independent science on air pollution and its health consequences.", url: "https://www.healtheffects.org" },
      { name: "OpenAQ", description: "Open-source platform aggregating real-time air quality data worldwide.", url: "https://openaq.org" },
    ],
  },
  {
    slug: "space-debris",
    title: "Clean Up Space Debris",
    domain: "energy",
    urgency: "medium",
    summary: "Remove orbital debris and establish governance frameworks before Kessler Syndrome makes low Earth orbit unusable.",
    whyItMatters: "Over 27,000 trackable debris objects orbit Earth at 28,000 km/h. A single collision can cascade into thousands of fragments. Satellites underpin GPS, weather forecasting, and global communications. Kessler Syndrome — a debris cascade — could shut humanity out of space for centuries.",
    teamsJson: "[]",
    teams: [
      { name: "ESA Clean Space Initiative", description: "European Space Agency program for sustainable use of space.", url: "https://www.esa.int/Enabling_Support/Space_Engineering_Technology/Clean_Space" },
      { name: "Astroscale", description: "Pioneer in space sustainability and end-of-life satellite services.", url: "https://astroscale.com" },
      { name: "ClearSpace", description: "ESA-contracted startup developing first active debris removal mission.", url: "https://clearspace.today" },
    ],
  },
  {
    slug: "gender-equality",
    title: "Achieve Full Gender Equality",
    domain: "inequality",
    urgency: "high",
    summary: "Dismantle systemic barriers preventing women and girls from reaching their full potential in every society.",
    whyItMatters: "Gender inequality costs the global economy $7 trillion per year in lost productivity. Girls who finish secondary school earn 25% more, have fewer children, and invest more in their communities. Gender equality is not just a moral imperative — it is the single highest-return investment humanity can make.",
    teamsJson: "[]",
    teams: [
      { name: "UN Women", description: "UN entity dedicated to gender equality and the empowerment of women.", url: "https://www.unwomen.org" },
      { name: "Girls Not Brides", description: "Global partnership committed to ending child marriage.", url: "https://www.girlsnotbrides.org" },
      { name: "Malala Fund", description: "Championing 12 years of free, quality education for every girl.", url: "https://malala.org" },
    ],
  },
];
