import { db, challengeSolutionsTable } from "@workspace/db";
import seedData from "../../data/nobel-solutions.json" with { type: "json" };
import { logger } from "../logger";

interface NobelSolutionSeed {
  challengeSlug: string;
  authorName: string;
  authorSlug: string;
  title: string;
  description: string;
  approach: string;
  link: string | null;
}

const SEED_SOLUTIONS = seedData as NobelSolutionSeed[];

/**
 * Idempotently seeds the Nobel-laureate-attributed challenge solutions into the
 * database. These are generated by `scripts/seed-nobel-solutions` (grounded in
 * each laureate's real, documented work) and committed as a snapshot via
 * `scripts/dump-nobel-solutions`.
 *
 * Replit's publish flow syncs the SCHEMA from dev to prod but never copies data,
 * so a freshly published production database has no laureate solutions. This
 * seeder bridges that gap on every boot. `challenge_solutions` has no unique
 * constraint on (challengeSlug, authorSlug), so we read the existing pairs and
 * insert only the rows that are missing — making repeated boots safe with no
 * duplicates. Failures are logged, never thrown, so seeding can never take the
 * server down.
 */
export async function seedNobelSolutions(): Promise<void> {
  try {
    if (SEED_SOLUTIONS.length === 0) {
      logger.info("No Nobel-solution seed data available, skipping seed");
      return;
    }

    // Existing (challengeSlug, authorSlug) pairs we must not duplicate.
    const existing = await db
      .select({
        challengeSlug: challengeSolutionsTable.challengeSlug,
        authorSlug: challengeSolutionsTable.authorSlug,
      })
      .from(challengeSolutionsTable);
    const taken = new Set(
      existing
        .filter((e) => e.authorSlug)
        .map((e) => `${e.challengeSlug}::${e.authorSlug}`),
    );

    const rows = SEED_SOLUTIONS.filter(
      (s) => !taken.has(`${s.challengeSlug}::${s.authorSlug}`),
    ).map((s) => ({
      challengeSlug: s.challengeSlug,
      userId: null,
      authorName: s.authorName,
      authorSlug: s.authorSlug,
      title: s.title,
      description: s.description,
      approach: s.approach,
      link: s.link,
    }));

    if (rows.length === 0) {
      logger.info(
        { total: SEED_SOLUTIONS.length },
        "Nobel-laureate solutions already present, skipping seed",
      );
      return;
    }

    await db.insert(challengeSolutionsTable).values(rows);

    logger.info(
      { total: SEED_SOLUTIONS.length, inserted: rows.length },
      "Nobel-laureate solutions seed complete",
    );
  } catch (err) {
    logger.error({ err }, "Failed to seed Nobel-laureate solutions");
  }
}
