import React from "react";
import { LegalPage } from "@/components/LegalPage";

export default function Terms() {
  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated="June 4, 2026"
      intro={
        <p>
          Welcome to Citizen Science. These Terms of Service ("Terms") govern your use of
          our website, apps, and features. By creating an account or using the service, you
          agree to these Terms. If you do not agree, please do not use Citizen Science.
        </p>
      }
      sections={[
        {
          heading: "Who can use Citizen Science",
          body: (
            <p>
              You must be at least 13 years old to use Citizen Science. If you are under the
              age of majority where you live, you should review these Terms with a parent or
              guardian. By using the service, you confirm that you meet these requirements.
            </p>
          ),
        },
        {
          heading: "Your account",
          body: (
            <p>
              You are responsible for keeping your login credentials secure and for all
              activity under your account. Please give us accurate information and keep it up
              to date. Notify us right away if you believe your account has been compromised.
            </p>
          ),
        },
        {
          heading: "Acceptable use",
          body: (
            <>
              <p>When using Citizen Science, you agree not to:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Break the law or encourage others to do so.</li>
                <li>Attempt to disrupt, reverse engineer, or gain unauthorized access to the service.</li>
                <li>Upload harmful, abusive, infringing, or misleading content.</li>
                <li>Misuse the AI features to generate unlawful or dangerous instructions.</li>
              </ul>
            </>
          ),
        },
        {
          heading: "Safety disclaimer",
          body: (
            <p>
              Citizen Science provides educational content and experiment suggestions for
              learning purposes only. Always follow proper safety precautions, use
              appropriate supervision, and exercise good judgment. Some experiments involve
              materials or activities that can be hazardous if done incorrectly. You are
              responsible for performing experiments safely, and you do so at your own risk.
            </p>
          ),
        },
        {
          heading: "Your content",
          body: (
            <p>
              You keep ownership of the experiments, notes, and observations you create. By
              storing content on Citizen Science, you grant us a limited license to host,
              store, and display that content solely to operate and improve the service for
              you. You are responsible for the content you submit.
            </p>
          ),
        },
        {
          heading: "AI-generated content",
          body: (
            <p>
              Some responses are generated by AI and may be inaccurate or incomplete. Do not
              rely on AI output as professional, medical, legal, or safety advice. Always
              verify important information independently before acting on it.
            </p>
          ),
        },
        {
          heading: "Service availability",
          body: (
            <p>
              We work hard to keep Citizen Science available, but we provide the service "as
              is" and may change, suspend, or discontinue features at any time. We do not
              guarantee that the service will always be uninterrupted or error-free.
            </p>
          ),
        },
        {
          heading: "Limitation of liability",
          body: (
            <p>
              To the fullest extent permitted by law, Citizen Science and its team will not
              be liable for any indirect, incidental, or consequential damages arising from
              your use of the service. Our total liability is limited to the amount you paid
              us, if any, in the twelve months before the claim.
            </p>
          ),
        },
        {
          heading: "Termination",
          body: (
            <p>
              You may stop using Citizen Science at any time and delete your account. We may
              suspend or terminate your access if you violate these Terms or use the service
              in a way that could harm others or us.
            </p>
          ),
        },
        {
          heading: "Changes to these Terms",
          body: (
            <p>
              We may update these Terms from time to time. When we make material changes, we
              will update the "Last updated" date above and, where appropriate, notify you in
              the app. Continued use after changes means you accept the updated Terms.
            </p>
          ),
        },
        {
          heading: "Contact us",
          body: (
            <p>
              Questions about these Terms? Reach us at{" "}
              <a href="mailto:support@citizen-science.org" className="text-blue-600 hover:text-blue-700">
                support@citizen-science.org
              </a>
              .
            </p>
          ),
        },
      ]}
    />
  );
}
